"""Create tables

Revision ID: b60d6c41579c
Revises:
Create Date: 2025-11-30 22:59:11.377273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b60d6c41579c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("crystals_cost", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("shield", sa.Integer(), nullable=False),
        sa.Column("champion_health", sa.Integer(), nullable=False),
        sa.Column(
            "faction",
            sa.Enum(
                "test",
                "DEMIREALM",
                "HOMODEUS",
                "NEUTRAL",
                "ORDER",
                "WILDS",
                name="cardfaction",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "card_type",
            sa.Enum(
                "test",
                "ALLY",
                "CHAMPION",
                "MERCENARY",
                "RELIC",
                name="cardtype",
            ),
            nullable=False,
        ),
        sa.Column("icon", sa.String(length=100), nullable=False),
        sa.Column(
            "start_card",
            sa.Enum(
                "FIRST_PLAYER",
                "SECOND_PLAYER",
                "OTHER",
                name="startcardplayer",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "champion_health >= 0",
            name=op.f("ck_cards_champion_health_non_negative"),
        ),
        sa.CheckConstraint(
            "crystals_cost >= 0", name=op.f("ck_cards_cost_non_negative")
        ),
        sa.CheckConstraint(
            "shield >= 0", name=op.f("ck_cards_shield_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=True),
        sa.Column("first_name", sa.String(length=20), nullable=True),
        sa.Column("last_name", sa.String(length=20), nullable=True),
        sa.Column("victories", sa.Integer(), nullable=False),
        sa.Column("defeats", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("chat_id", name=op.f("uq_users_chat_id")),
    )
    op.create_table(
        "card_effects",
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "ALL_FRACTIONS",
                "ATTACK",
                "CHAMPION_DESTROY",
                "CHOOSE_CARD_FROM_MARKET",
                "COPY_ALL_EFFECTS_HOMODEUS",
                "COPY_EFFECT",
                "CRYSTAL",
                "CARD_DESTROY",
                "DOUBLE_CHOICE",
                "DOUBLE_DAMAGE",
                "ENEMY_LOSE_MIGHT",
                "HEALING",
                "INVULNERABILITY_ALL",
                "INVULNERABILITY_CARD",
                "MIGHT",
                "NONE",
                "PLAY_HOMODEUS_CHAMPION_FROM_MARKET",
                "SPECIAL",
                "TAKE_CARD",
                "TAKE_CARD_FROM_MARKET",
                "TAKE_CHAMPION_FROM_RESET",
                "TAKE_DEMIREALM_CARD",
                "TAKE_MERCENARY_FROM_RESET",
                name="cardaction",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column(
            "effect_type",
            sa.Enum(
                "BASE", "CONDITIONAL", name="effecttype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "condition_type",
            sa.Enum(
                "CARD_FROM_HAND",
                "CARD_ON_TABLE",
                "CHAMPION_ON_TABLE",
                "DEMIREALM_IN_RESET",
                "DEMIREALM_ON_TABLE",
                "ENEMY_HAS_CHAMPION",
                "GENERAL_DRACONARIUS",
                "HOMODEUS_ON_TABLE",
                "MASTERY",
                "NONE",
                "ORDER_ON_TABLE",
                "PLAY_FROM_HAND",
                "PLAYER_HEALTH",
                "PLUS_VALUE_FOR_EACH_HOMODEUS_CHAMPION_IN_GAME",
                "PLUS_TWO_FOR_EACH_DEMIREALM_IN_RESET",
                "PLUS_TWO_FOR_EACH_WILDS_IN_PLAY",
                "WILDS_HOMODEUS_DEMIREALM_ON_TABLE",
                "WILDS_ON_TABLE",
                "WHD_CHAMPION",
                name="conditiontype",
            ),
            nullable=True,
        ),
        sa.Column("condition_value", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_card_effects_card_id_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_effects")),
    )
    op.create_table(
        "games",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING",
                "IN_PROGRESS",
                "FINISHED",
                name="gamestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("player1_id", sa.BigInteger(), nullable=False),
        sa.Column("player2_id", sa.BigInteger(), nullable=True),
        sa.Column("active_player_id", sa.BigInteger(), nullable=True),
        sa.Column("non_active_player_id", sa.BigInteger(), nullable=True),
        sa.Column("invite_token", sa.String(length=32), nullable=True),
        sa.Column("winner_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_player_id"],
            ["users.id"],
            name=op.f("fk_games_active_player_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["non_active_player_id"],
            ["users.id"],
            name=op.f("fk_games_non_active_player_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["player1_id"],
            ["users.id"],
            name=op.f("fk_games_player1_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["player2_id"],
            ["users.id"],
            name=op.f("fk_games_player2_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"], ["users.id"], name=op.f("fk_games_winner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_games")),
        sa.UniqueConstraint(
            "invite_token", name=op.f("uq_games_invite_token")
        ),
    )
    op.create_table(
        "market_slots",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_market_slots_card_id_cards"),
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_market_slots_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_slots")),
    )
    op.create_table(
        "player_states",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("health", sa.Integer(), nullable=False),
        sa.Column("mastery", sa.Integer(), nullable=False),
        sa.Column("crystals", sa.Integer(), nullable=False),
        sa.Column("power", sa.Integer(), nullable=False),
        sa.Column("shield", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "wilds_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "order_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "homodeus_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "demirealm_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "invulnerability",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_player_states_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["users.id"],
            name=op.f("fk_player_states_player_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_states")),
    )
    op.create_table(
        "player_card_instances",
        sa.Column("player_state_id", sa.Integer(), nullable=True),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column(
            "zone",
            sa.Enum(
                "CHAMPION",
                "COMMON_DECK",
                "DISCARD",
                "EXILED",
                "HAND",
                "IN_PLAY",
                "MARKET",
                "PLAYER_DECK",
                name="cardzone",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "position_on_market",
            sa.Integer(),
            server_default=sa.text("NULL"),
            nullable=True,
        ),
        sa.Column(
            "delete_mercenary",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
        sa.Column(
            "invulnerability",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(zone != 'MARKET') OR (position_on_market IS NOT NULL)",
            name=op.f("ck_player_card_instances_market_position_required"),
        ),
        sa.CheckConstraint(
            "(zone = 'MARKET') OR (position_on_market IS NULL)",
            name=op.f("ck_player_card_instances_position_only_for_market"),
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_player_card_instances_card_id_cards"),
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_player_card_instances_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_state_id"],
            ["player_states.id"],
            name=op.f(
                "fk_player_card_instances_player_state_id_player_states"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_card_instances")),
        sa.UniqueConstraint("game_id", "card_id", name="uq_game_card"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_card_instances")
    op.drop_table("player_states")
    op.drop_table("market_slots")
    op.drop_table("games")
    op.drop_table("card_effects")
    op.drop_table("users")
    op.drop_table("cards")
    # ### end Alembic commands ###
