"""PlayState table shield

Revision ID: 6337458f3a9c
Revises: bd08a0f96926
Create Date: 2025-09-11 20:39:22.947701

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6337458f3a9c"
down_revision: Union[str, Sequence[str], None] = "bd08a0f96926"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_states",
        sa.Column("shield", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player_states", "shield")
    # ### end Alembic commands ###
