"""Change player_instance

Revision ID: d05c9e389528
Revises: 42f1e704a199
Create Date: 2025-10-11 00:42:32.645968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d05c9e389528"
down_revision: Union[str, Sequence[str], None] = "42f1e704a199"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_card_instances",
        sa.Column(
            "position_on_market",
            sa.Integer(),
            server_default=sa.text("NULL"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player_card_instances", "position_on_market")
    # ### end Alembic commands ###
