"""Create tables

Revision ID: 183882830b4c
Revises:
Create Date: 2025-12-10 22:45:40.911417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "183882830b4c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cards",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("crystals_cost", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("shield", sa.Integer(), nullable=False),
        sa.Column("champion_health", sa.Integer(), nullable=False),
        sa.Column(
            "faction",
            sa.Enum(
                "demirealm",
                "homodeus",
                "neutral",
                "order",
                "wilds",
                name="cardfaction",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "card_type",
            sa.Enum(
                "ally",
                "champion",
                "mercenary",
                "relic",
                name="cardtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("icon", sa.String(length=100), nullable=False),
        sa.Column(
            "start_card",
            sa.Enum(
                "first_player",
                "second_player",
                "other",
                name="startcardplayer",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "champion_health >= 0",
            name=op.f("ck_cards_champion_health_non_negative"),
        ),
        sa.CheckConstraint(
            "crystals_cost >= 0", name=op.f("ck_cards_cost_non_negative")
        ),
        sa.CheckConstraint(
            "shield >= 0", name=op.f("ck_cards_shield_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=True),
        sa.Column("first_name", sa.String(length=20), nullable=True),
        sa.Column("last_name", sa.String(length=20), nullable=True),
        sa.Column("victories", sa.Integer(), nullable=False),
        sa.Column("defeats", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("chat_id", name=op.f("uq_users_chat_id")),
    )
    op.create_table(
        "card_effects",
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "all_fractions",
                "attack",
                "champion_destroy",
                "choose_card_from_market",
                "copy_all_effects_homodeus",
                "copy_effect",
                "crystal",
                "card_destroy",
                "double_choice",
                "double_damage",
                "enemy_lose_might",
                "healing",
                "invulnerability_all",
                "invulnerability_card",
                "might",
                "none",
                "play_homodeus_champion_from_market",
                "special",
                "take_card",
                "take_card_from_market",
                "take_champion_from_reset",
                "take_demirealm_card",
                "take_mercenary_from_reset",
                name="cardaction",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column(
            "effect_type",
            sa.Enum(
                "base", "conditional", name="effecttype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "condition_type",
            sa.Enum(
                "card_from_hand",
                "card_on_table",
                "champion_on_table",
                "demirealm_in_reset",
                "demirealm_on_table",
                "enemy_has_champion",
                "general_draconarius",
                "homodeus_on_table",
                "mastery",
                "none",
                "order_on_table",
                "play_from_hand",
                "player_health",
                "plus_value_for_each_homodeus_champion_in_game",
                "plus_two_for_each_demirealm_in_reset",
                "plus_two_for_each_wilds_in_play",
                "wilds_homodeus_demirealm_on_table",
                "wilds_on_table",
                "whd_champion",
                name="conditiontype",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("condition_value", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_card_effects_card_id_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_effects")),
    )
    op.create_table(
        "games",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "waiting",
                "in_progress",
                "finished",
                name="gamestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("player1_id", sa.BigInteger(), nullable=False),
        sa.Column("player2_id", sa.BigInteger(), nullable=True),
        sa.Column("active_player_id", sa.BigInteger(), nullable=True),
        sa.Column("non_active_player_id", sa.BigInteger(), nullable=True),
        sa.Column("invite_token", sa.String(length=32), nullable=True),
        sa.Column("winner_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_player_id"],
            ["users.id"],
            name=op.f("fk_games_active_player_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["non_active_player_id"],
            ["users.id"],
            name=op.f("fk_games_non_active_player_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["player1_id"],
            ["users.id"],
            name=op.f("fk_games_player1_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["player2_id"],
            ["users.id"],
            name=op.f("fk_games_player2_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"], ["users.id"], name=op.f("fk_games_winner_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_games")),
        sa.UniqueConstraint(
            "invite_token", name=op.f("uq_games_invite_token")
        ),
    )
    op.create_table(
        "market_slots",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_market_slots_card_id_cards"),
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_market_slots_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_slots")),
    )
    op.create_table(
        "player_states",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("health", sa.Integer(), nullable=False),
        sa.Column("mastery", sa.Integer(), nullable=False),
        sa.Column("crystals", sa.Integer(), nullable=False),
        sa.Column("power", sa.Integer(), nullable=False),
        sa.Column("shield", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "wilds_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "order_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "homodeus_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "demirealm_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "invulnerability",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
        sa.Column(
            "concentration",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_player_states_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["users.id"],
            name=op.f("fk_player_states_player_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_states")),
    )
    op.create_table(
        "player_card_instances",
        sa.Column("player_state_id", sa.Integer(), nullable=True),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column(
            "zone",
            sa.Enum(
                "champion",
                "common_deck",
                "discard",
                "exiled",
                "hand",
                "in_play",
                "market",
                "player_deck",
                name="cardzone",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "position_on_market",
            sa.Integer(),
            server_default=sa.text("NULL"),
            nullable=True,
        ),
        sa.Column(
            "delete_mercenary",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
        sa.Column(
            "invulnerability",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(zone != 'market') OR (position_on_market IS NOT NULL)",
            name=op.f("ck_player_card_instances_market_position_required"),
        ),
        sa.CheckConstraint(
            "(zone = 'market') OR (position_on_market IS NULL)",
            name=op.f("ck_player_card_instances_position_only_for_market"),
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_player_card_instances_card_id_cards"),
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_player_card_instances_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_state_id"],
            ["player_states.id"],
            name=op.f(
                "fk_player_card_instances_player_state_id_player_states"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_card_instances")),
        sa.UniqueConstraint("game_id", "card_id", name="uq_game_card"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_card_instances")
    op.drop_table("player_states")
    op.drop_table("market_slots")
    op.drop_table("games")
    op.drop_table("card_effects")
    op.drop_table("users")
    op.drop_table("cards")
    # ### end Alembic commands ###
