"""Change card table

Revision ID: bd08a0f96926
Revises: d17d3e3cb456
Create Date: 2025-09-03 12:14:16.903385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd08a0f96926"
down_revision: Union[str, Sequence[str], None] = "d17d3e3cb456"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_states",
        sa.Column(
            "wilds_count", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "player_states",
        sa.Column(
            "order_count", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "player_states",
        sa.Column(
            "homodeus_count", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "player_states",
        sa.Column(
            "demirealm_count", sa.Integer(), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player_states", "demirealm_count")
    op.drop_column("player_states", "homodeus_count")
    op.drop_column("player_states", "order_count")
    op.drop_column("player_states", "wilds_count")
    # ### end Alembic commands ###
