"""mercenary_delete

Revision ID: f0d00f5b40a4
Revises: 726d5950237d
Create Date: 2025-10-02 13:24:09.551542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0d00f5b40a4"
down_revision: Union[str, Sequence[str], None] = "726d5950237d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_card_instances",
        sa.Column(
            "delete_mercenamy",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player_card_instances", "delete_mercenamy")
    # ### end Alembic commands ###
