"""Create

Revision ID: 5cfd8c1f1899
Revises: 7b2b640a7dcd
Create Date: 2025-10-13 16:37:42.572051

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5cfd8c1f1899"
down_revision: Union[str, Sequence[str], None] = "7b2b640a7dcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_player_card_instances_card_id"),
        "player_card_instances",
        ["card_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_player_card_instances_card_id"),
        "player_card_instances",
        type_="unique",
    )
    # ### end Alembic commands ###
