"""concentration

Revision ID: 4469e6f4cf8b
Revises: 4297f2a1da7b
Create Date: 2025-12-06 14:59:53.181499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4469e6f4cf8b"
down_revision: Union[str, Sequence[str], None] = "4297f2a1da7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_states",
        sa.Column(
            "concentration",
            sa.Boolean(),
            server_default=sa.text("FALSE"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player_states", "concentration")
    # ### end Alembic commands ###
